version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - SEASON=${SEASON:-2026}
      - SIMULATOR=${SIMULATOR:-loop}
    volumes:
      - ./src:/src
      - ./tests:/tests
